# .github/workflows/ci.yml

name: Build and Deploy CDS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the CDS project
        run: npx cds build

      - name: Run tests (optional)
        run: npm test
        continue-on-error: true # If you don't have tests yet


    # OPTIONAL: Add your deploy command here
    # - name: Deploy to destination
    #   run: ./deploy.sh or npx cds deploy --to ...
